export const post = {
  add: 'ADD_POST',
  edit: 'EDIT_POST',
  delete: 'DELETE_POST',
  pending: 'POST_PENDING',
  fulfilled: 'POST_FULFILLED',
  rejected: 'POST_REJECTED',
  reset: 'RESET_POST',
  get: 'GET_POSTS',
  setPosts: 'SET_POSTS',
  updateSuccess: 'UPDATE_SUCCESS',
  deleteSuccess: 'DELETE_SUCCESS',
  setLoading: 'SET_LOADING',
  updatePending: 'UPDATE_PENDING',
  updateRejected: 'UPDATE_REJECTED',
  deletePending: 'DELETE_PENDING',
  deleteRejected: 'DELETE_REJECTED',
  addPending: 'ADD_PENDING',
  addRejected: 'ADD_REJECTED',
  addSuccess: 'ADD_SUCCESS',
};
